
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (1, 'Justis Waghorn', 'jwaghorn0', 'jhSfDGnC', '9 Farmco Crossing', 'Prime', 737);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (2, 'Loretta Quiney', 'lquiney1', 'OI6jW1k4902l', '5 Burning Wood Lane', 'Elite', 864);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (3, 'Chrystal Wethered', 'cwethered2', 'PiZVFDVw79', '00524 Maple Hill', 'Elite', 818);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (4, 'Tiffi Goulter', 'tgoulter3', 'BYLK02', '71297 Menomonie Avenue', 'Prime', 133);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (5, 'Gratia McDuall', 'gmcduall4', 'MhlLuA', '679 Spohn Drive', 'Elite', 282);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (6, 'Joey Giovanni', 'jgiovanni5', 'h754oMXieP', '237 Bartelt Lane', 'Elite', 44);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (7, 'Kirby Kunisch', 'kkunisch6', 'kbENkfesN7', '79 Prentice Circle', 'Prime', 0);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (8, 'Humfried Phlipon', 'hphlipon7', 'T5FhtNxsU0Z', '82473 Susan Place', 'Elite', 152);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (9, 'Warden Edmeads', 'wedmeads8', 'N0U9G0FH', '75 Armistice Court', 'Normal', 710);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (10, 'Silvana Leaf', 'sleaf9', '65ahgDdT', '92 Forest Run Avenue', 'Normal', 502);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (11, 'Emlyn Wyles', 'ewylesa', 'VwvQJmhnYn1a', '648 Debs Street', 'Elite', 194);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (12, 'Howie Conwell', 'hconwellb', 'gGvnX8sRD', '5 Buhler Court', 'Elite', 684);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (13, 'Talbot Woodroffe', 'twoodroffec', 'AUpE8ALZPw', '6440 Prairie Rose Road', 'Normal', 463);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (14, 'Dasya Chippin', 'dchippind', '07vtCVfHSXo', '188 Eggendart Avenue', 'Normal', 459);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (15, 'Michael Gabbett', 'mgabbette', 'CTdlcNe', '775 Cascade Circle', 'Normal', 358);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (16, 'Lyndsay Arno', 'larnof', 'm000YklXj', '41 Mccormick Road', 'Elite', 123);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (17, 'Kaia Lancaster', 'klancasterg', 'pkz3b5', '949 Dakota Street', 'Normal', 795);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (18, 'Astrix Westoff', 'awestoffh', 'J2RZ3Xb6r', '22912 Old Shore Road', 'Prime', 58);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (19, 'Marcelia Redhouse', 'mredhousei', '3CtK2M', '890 Forest Dale Place', 'Elite', 658);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (20, 'Sonny Skett', 'sskettj', 'mvYNdD6wt3U', '3721 Drewry Pass', 'Normal', 23);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (21, 'Ronald Peasey', 'rpeaseyk', '1QsyqYJk1', '65 Esker Crossing', 'Normal', 827);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (22, 'Kelwin Becom', 'kbecoml', 'Pt4n8B', '57 Loeprich Park', 'Prime', 546);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (23, 'Joelly Moehle', 'jmoehlem', '8YvICDxHZ', '069 Stephen Court', 'Normal', 263);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (24, 'Caryl Petyankin', 'cpetyankinn', '2BGo21Uqgy8L', '54 Bluestem Junction', 'Normal', 241);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (25, 'Hoebart Wafer', 'hwafero', 'CDvUNYZV31', '1 Charing Cross Center', 'Prime', 616);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (26, 'Conrad Dryden', 'cdrydenp', 'ggUD9nRnhNP', '9 Helena Trail', 'Normal', 108);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (27, 'Brinna Allpress', 'ballpressq', 'ABDcNi5', '7 Rusk Point', 'Prime', 661);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (28, 'Clarine Durek', 'cdurekr', 'RoJ6JJf', '1441 Boyd Lane', 'Normal', 637);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (29, 'Melisa Childrens', 'mchildrenss', 'gYl71t', '2937 Nancy Terrace', 'Normal', 386);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (30, 'Patin Suart', 'psuartt', 'JqwvGOYyRVe', '860 Melvin Drive', 'Elite', 899);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (31, 'Gail Gouldstone', 'ggouldstoneu', 'okplOHlOX2fg', '33 Dawn Way', 'Prime', 141);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (32, 'Irita Ovendon', 'iovendonv', 'xJP4wZAihcS', '52813 Lukken Plaza', 'Elite', 282);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (33, 'Ozzie Diano', 'odianow', 'K15xNDqOQJZ', '1 Lerdahl Point', 'Normal', 245);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (34, 'Annabell Dawltrey', 'adawltreyx', 'Hwn9Fsi5TKA', '799 Gina Parkway', 'Prime', 189);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (35, 'Nollie Penburton', 'npenburtony', 'HOignE5R', '6366 Hayes Road', 'Prime', 532);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (36, 'Gennifer Longbottom', 'glongbottomz', 'dh37FI8Fn', '9 Claremont Center', 'Normal', 883);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (37, 'Mariann Northam', 'mnortham10', '5D8K3ULaKCqn', '797 Forest Run Way', 'Elite', 581);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (38, 'Matthus Bee', 'mbee11', 'bD3KzZQjLUO', '5161 Morningstar Court', 'Elite', 129);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (39, 'Vinnie Dallison', 'vdallison12', 'MEbg2c', '8371 Rutledge Avenue', 'Normal', 172);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (40, 'Martina Blondelle', 'mblondelle13', 'Ia8Eoqu4', '13 Pierstorff Plaza', 'Normal', 232);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (41, 'Beltran Tummons', 'btummons14', 'eAdTvHvgIrvt', '4 Arapahoe Alley', 'Prime', 672);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (42, 'Teddy Morl', 'tmorl15', 'tNoyk8naK', '167 Ilene Crossing', 'Prime', 866);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (43, 'Kennett Shotbolt', 'kshotbolt16', 'uC0Zfxtj', '27 Spenser Place', 'Elite', 367);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (44, 'Bevan Domel', 'bdomel17', 'CgbJswPU1e', '529 6th Avenue', 'Prime', 776);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (45, 'Christa Rooney', 'crooney18', 'Dy1Kb2RTNE', '42066 Russell Plaza', 'Elite', 443);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (46, 'Mendel Riping', 'mriping19', '4lOteO6', '909 Porter Crossing', 'Elite', 632);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (47, 'Filip Duchatel', 'fduchatel1a', 'ZjxVdctlzBk', '5 Forest Dale Place', 'Normal', 875);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (48, 'Patricia Jozefczak', 'pjozefczak1b', 'ltz2GPBu8', '094 Maryland Lane', 'Normal', 383);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (49, 'Faydra Girardez', 'fgirardez1c', 'u0jsIQtW1RG', '521 Melody Drive', 'Elite', 982);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (50, 'Sue Creed', 'screed1d', 'ql686ZzNypB', '40353 Florence Parkway', 'Normal', 29);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (51, 'Eldridge Huburn', 'ehuburn1e', 'nydleDyb', '2834 Bartelt Circle', 'Normal', 712);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (52, 'Worden Easom', 'weasom1f', 'k9kEbTEew', '3 Loomis Junction', 'Normal', 972);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (53, 'Franny Marzella', 'fmarzella1g', 'yDujuzLFFyc3', '4 Carpenter Crossing', 'Elite', 364);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (54, 'Daven Pedycan', 'dpedycan1h', '2e70fIaufI2N', '98 Pennsylvania Pass', 'Prime', 462);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (55, 'Karl MacClay', 'kmacclay1i', 'CGTD8aie', '8 Jenifer Pass', 'Prime', 979);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (56, 'Riki Flaws', 'rflaws1j', 'ULYfu9n4kNfQ', '5 Transport Avenue', 'Elite', 501);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (57, 'Nate Dailey', 'ndailey1k', '5jFur0', '55573 Esker Park', 'Normal', 23);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (58, 'Alyse Gullis', 'agullis1l', 'idnDjQ6ozN', '04162 Karstens Point', 'Prime', 752);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (59, 'Gerrilee De Marchi', 'gde1m', 'tvkuu9GZnN', '181 Doe Crossing Road', 'Normal', 619);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (60, 'Theodor Auld', 'tauld1n', 'kYy0exB', '58079 Kennedy Pass', 'Prime', 863);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (61, 'Estel Millmore', 'emillmore1o', '7BYHBr', '2 Porter Drive', 'Normal', 793);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (62, 'Theressa Killeen', 'tkilleen1p', 'oJBhwf', '7405 Glendale Drive', 'Normal', 309);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (63, 'Nikolaos Red', 'nred1q', 'jya496uhqzN', '6048 Messerschmidt Trail', 'Prime', 380);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (64, 'Sandy Aleksandrov', 'saleksandrov1r', 'UROSL3N', '6516 Elgar Point', 'Prime', 431);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (65, 'Prue Du Barry', 'pdu1s', 'XC5sTxkd', '2811 Lukken Alley', 'Normal', 274);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (66, 'Casar Mathou', 'cmathou1t', 'BbbS9mmrHPD', '6 Maywood Circle', 'Prime', 797);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (67, 'Adiana Mariet', 'amariet1u', 'RchWAm2jd', '70983 Bluejay Avenue', 'Prime', 407);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (68, 'Erma L''Hommeau', 'elhommeau1v', 'd3XvFch', '3 Butterfield Parkway', 'Prime', 396);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (69, 'Blinnie Ghidoni', 'bghidoni1w', 'OZM4hz7Ll', '85280 Gerald Way', 'Normal', 161);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (70, 'Cam Ert', 'cert1x', 'bNF8AZiSR73', '0188 Dayton Court', 'Elite', 597);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (71, 'Rudiger Bantick', 'rbantick1y', 'KIza4M2cRmfl', '7 Northwestern Crossing', 'Elite', 738);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (72, 'Jobi Germaine', 'jgermaine1z', 's7QNqQZERBJ', '9540 Welch Hill', 'Normal', 534);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (73, 'Sella Tuvey', 'stuvey20', 'WZjbelh1yh', '1535 Walton Avenue', 'Elite', 323);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (74, 'Lila Chominski', 'lchominski21', 'fZwxyZ7VDvS', '97 Judy Terrace', 'Prime', 406);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (75, 'Margret Giampietro', 'mgiampietro22', 'eS6DzLTwVYD', '573 Pine View Court', 'Elite', 35);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (76, 'Morgun Cordelle', 'mcordelle23', 'A2AFMReULI8H', '625 Merchant Parkway', 'Prime', 304);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (77, 'Calv Battson', 'cbattson24', 'rHau2BorfnM', '0440 Bellgrove Avenue', 'Prime', 136);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (78, 'Kyle Lyndon', 'klyndon25', '66irgWK', '2256 Milwaukee Center', 'Elite', 742);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (79, 'Karie Jordan', 'kjordan26', 'gGJyOQ', '2 Jenna Place', 'Prime', 726);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (80, 'Anderea Kerrane', 'akerrane27', 'FwkzEWrX', '2132 Dahle Center', 'Elite', 20);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (81, 'Zed Heis', 'zheis28', 'I7haoOGnU', '558 Lakewood Gardens Street', 'Prime', 994);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (82, 'Blythe Beacroft', 'bbeacroft29', 'c0XNuS3p', '37 Chinook Point', 'Prime', 898);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (83, 'Husain Kingzett', 'hkingzett2a', 'x7PfAq', '0 Express Crossing', 'Elite', 761);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (84, 'Rog Erangy', 'rerangy2b', '1GYkWw1AJ31Y', '63 American Ash Plaza', 'Prime', 448);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (85, 'Hubie Milvarnie', 'hmilvarnie2c', 'IU6gqYN8', '6 Cherokee Alley', 'Normal', 962);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (86, 'Basia Meaking', 'bmeaking2d', 'tDOm4G7jL', '804 Schmedeman Center', 'Prime', 475);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (87, 'Thebault Yeude', 'tyeude2e', '75TLdzo', '72046 Orin Plaza', 'Prime', 826);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (88, 'Dosi Van der Kruys', 'dvan2f', 'kBaXG0WVn5I', '2 Forster Street', 'Normal', 740);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (89, 'Hallsy Massy', 'hmassy2g', 'uJkGMimZO', '05389 Mockingbird Drive', 'Elite', 279);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (90, 'Kitti Parris', 'kparris2h', 's3uVqRfZj', '355 Kenwood Terrace', 'Normal', 671);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (91, 'Bo Potkins', 'bpotkins2i', 'AKwY68NZ', '331 Brickson Park Plaza', 'Elite', 508);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (92, 'Tildie Dautry', 'tdautry2j', 'p2WPz5pigi', '01 Judy Park', 'Prime', 98);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (93, 'Hurleigh MacMenamin', 'hmacmenamin2k', 'QzOu9iy', '676 Basil Terrace', 'Elite', 12);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (94, 'Jessi Nicolls', 'jnicolls2l', 'qkqxdMwcb', '61869 Melvin Street', 'Prime', 385);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (95, 'Mahalia Mompesson', 'mmompesson2m', '2Z2WVNKOys', '1 Lighthouse Bay Road', 'Prime', 33);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (96, 'Dolorita Aldcorn', 'daldcorn2n', 'qzZwAz', '40 Badeau Pass', 'Prime', 205);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (97, 'Junia Stennine', 'jstennine2o', 'XBSYEMk4E', '168 Starling Court', 'Prime', 885);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (98, 'See Mayfield', 'smayfield2p', 'okhaUdrb', '6 Hudson Pass', 'Elite', 509);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (99, 'Edna Nordass', 'enordass2q', '4fm0Ph54CHk', '21234 Alpine Circle', 'Elite', 755);
insert into CUSTOMER (Customer_Id, Name, Username, Password, Address, Membership, Wallet) values (100, 'Angelita Woolford', 'awoolford2r', 'IwfekBU0WpS0', '07501 Pierstorff Parkway', 'Elite', 466);