
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (1, 'Electronics', 5);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (2, 'Books', 3);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (3, 'Outdoors', 2);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (4, 'Tools', 8);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (5, 'Grocery', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (6, 'Baby', 6);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (7, 'Sports', 4);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (8, 'Clothing', 10);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (9, 'Footwear', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (10, 'Garden', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (13, 'Health', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (14, 'Jewelry', 2);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (15, 'Gaming', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (16, 'Toys', 8);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (17, 'Home Appliances', 5);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (18, 'Watches', 8);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (19, 'Music', 2);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (21, 'Beauty', 1);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (23, 'Software', 5);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (24, 'Pet Supplies', 3);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (25, 'Automotive', 7);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (26, 'Luggage and Bags', 4);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (27, 'Furniture', 8);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (28, 'Stationery', 3);
insert into CATEGORY (Category_Id, Name, No_Of_Products) values (30, 'Home Decor', 1);